src/ESGI/BlogBundle/Entity/Image.php
<?php

namespace ESGI\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image.
 *
 * @ORM\Table()
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity(repositoryClass="ESGI\BlogBundle\Entity\ImageRepository")
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255)
     */
    private $path;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    /**
     * @var Article
     * @ORM\OneToMany(targetEntity="ESGI\BlogBundle\Entity\Article", cascade={"persist"}, mappedBy="image")
     * @ORM\JoinColumn(name="article_id", referencedColumnName="id")
     */
    private $articles;

    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;

    private $tempFilename;

    /**
     * Get id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set path.
     *
     * @param string $path
     *
     * @return Image
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path.
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set alt.
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt.
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /***********/
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->path) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->path;

            // On réinitialise les valeurs des attributs url et alt
            $this->path = null;
            $this->alt = null;
        }
    }

    public function getFile()
    {
        return $this->file;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
            return;
        }

        // Le nom du fichier est un identifiant unique, on doit juste stocker également son extension
        $uniqName = uniqid().'.'.$this->file->guessExtension();
        $this->path = $uniqName;

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
            return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->path;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
            $this->getUploadRootDir(), // Le répertoire de destination
            $this->path   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->path;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/img/content';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getPath();
    }
    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->articles = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add articles.
     *
     * @param \ESGI\BlogBundle\Entity\Article $articles
     *
     * @return Image
     */
    public function addArticle(\ESGI\BlogBundle\Entity\Article $articles)
    {
        $this->articles[] = $articles;

        return $this;
    }

    /**
     * Remove articles.
     *
     * @param \ESGI\BlogBundle\Entity\Article $articles
     */
    public function removeArticle(\ESGI\BlogBundle\Entity\Article $articles)
    {
        $this->articles->removeElement($articles);
    }

    /**
     * Get articles.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getArticles()
    {
        return $this->articles;
    }

    public function __toString() {
        return $this->getPath();
    }
}

src/ESGI/BlogBundle/Form/ArticleType.php
<?php

namespace ESGI\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ArticleType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('body')
            ->add('isPublished',  'checkbox', array(  'label'  => 'Publier'))
            ->add('image', new ImageType())
            ->add('isCommented', 'checkbox', array(  'label'  => 'Autorisé les commentaires'))
            ->add('category', 'entity', array(
                                                'class'    => 'ESGIBlogBundle:Category',
                                                'property' => 'name',
                                                'multiple' => false, ))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ESGI\BlogBundle\Entity\Article',
            'intention' => 'task_contenthsh',
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'esgi_blogbundle_article';
    }
}

src/ESGI/BlogBundle/Controller/ArticleController.php
<?php

namespace ESGI\BlogBundle\Controller;

use ESGI\BlogBundle\Entity\SuggestArticle;
use ESGI\BlogBundle\Form\SuggestArticleType;
use ESGI\BlogBundle\Entity\Article;
use ESGI\BlogBundle\Form\ArticleType;
use Symfony\Component\HttpFoundation\Request;
use FOS\RestBundle\Controller\FOSRestController;

class ArticleController extends FOSRestController
{
    public function addAction()
    {
        $article = new Article();
        $categories = $this->getDoctrine()->getManager()->getRepository("ESGIBlogBundle:Category")->findAll();
        // On crée le FormBuilder grâce à la méthode du contrôleur
        $form = $this->createForm(new ArticleType(), $article);

        $request = $this->get('request');

        // On vérifie qu'elle est de type POST
        if ($request->getMethod() == 'POST') {
            // On fait le lien Requête <-> Formulaire
            $form->handleRequest($request);

            // Vérifier si les entrées sont correctes
            if ($form->isValid()) {
                // On enregistre l'objet en base de donnée
                $em = $this->getDoctrine()->getManager();
                $user = $this->container->get('security.context')->getToken()->getUser();
                $article->setUser($user);
                $em->persist($article);
                $em->flush();

                // On redirige vers la page de visualisation du contenu nouvellement créé
                return $this->redirect($this->generateUrl('see', array('id' => $article->getId())));
            }
        }

        return $this->render('ESGIBlogBundle:Article:add.html.twig', array(
            'form' => $form->createView(),
            'categories' => $categories,
        ));
    }

    public function seeAction(Article $article)
    {
        $categories = $this->getDoctrine()->getManager()->getRepository("ESGIBlogBundle:Category")->findAll();
        // Récupération du menu choisi.
        $em = $this->getDoctrine()->getManager();
        $article = $em->getRepository('ESGIBlogBundle:Article')
                    ->find($article->getId());

        return $this->render('ESGIBlogBundle:Article:see.html.twig', array(
                'article' => $article, 
                'categories' => $categories,

        ));
    }

    public function deleteAction(Article $article)
    {
        $categories = $this->getDoctrine()->getManager()->getRepository("ESGIBlogBundle:Category")->findAll();
        $form = $this->createFormBuilder()->getForm();

        $request = $this->get('request');
        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);

            if ($form->isValid()) {
                // On supprime l'article
                $em = $this->getDoctrine()->getManager();
                $user = $this->container->get('security.context')->getToken()->getUser();
                $article->setUser($user);
                $em->remove($article);
                $em->flush();

                // On définit un message flash
                $this->get('session')->getFlashBag()->add('info', 'Article bien supprimé');

                // Puis on redirige vers les articles
                return $this->redirect($this->generateUrl('articles'));
            }
        }

        return $this->render('ESGIBlogBundle:Article:delete.html.twig', array(
                'article' => $article,
                'form'    => $form->createView(),
                'categories' => $categories,
            ));
    }

    /**
     * Fetch all articles published with pagination.
     *
     * @param $page
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function articlesAction($page, $id)
    {
        $numberContentsByPage = 3;
        // Pour récupérer la liste de tous les articles : on utilise findAll()
        // Sinon, on créer une pagination avec un nombre de contenu constant pour chaque page.

        $articles = null;
        $categories = $this->getDoctrine()->getManager()->getRepository("ESGIBlogBundle:Category")->findAll();

        if ($id === 0)
        {
            $articles = $this->getDoctrine()
                ->getManager()
                ->getRepository('ESGIBlogBundle:Article')
                ->getArticlesPublished($numberContentsByPage, $page);
        } else {
            $category = $this->getDoctrine()->getManager()->getRepository("ESGIBlogBundle:Category")->find($id);
            $articles =  $this->getDoctrine()->getManager()
                ->getRepository('ESGIBlogBundle:Article')
                ->getArticlesPublishedCategory($numberContentsByPage, $page, $category);
        }


        /*
        $articles = $this->getDoctrine()
            ->getManager()
            ->getRepository('ESGIBlogBundle:Article')
            ->getArticlesPublished($numberContentsByPage, $page);*/

        return $this->render('ESGIBlogBundle:Article:articles.html.twig', array(
            'articles' => $articles,
            'categories' => $categories,
            'page' => $page,
            'numberPage' => ceil(count($articles) / $numberContentsByPage),
        ));
    }

    public function suggestAction($page)
    {
        $numberContentsByPage = 9;
        // Pour récupérer la liste de tous les articles : on utilise findAll()
        // Sinon, on créer une pagination avec un nombre de contenu constant pour chaque page.
        $articles = $this->getDoctrine()
            ->getManager()
            ->getRepository('ESGIBlogBundle:SuggestArticle')
            ->getArticlesPaginator($numberContentsByPage, $page);

        return $this->render('ESGIBlogBundle:Article:suggest.html.twig', array(
            'articles' => $articles,
            'page' => $page,
            'numberPage' => ceil(count($articles) / $numberContentsByPage),
            'categories' => $categories,
        ));
    }

    public function suggestArticleAction()
    {
        $suggestArticle = new SuggestArticle();

        // On crée le FormBuilder grâce à la méthode du contrôleur
        $form = $this->createForm(new SuggestArticleType(), $suggestArticle);

        $request = $this->get('request');

        // On vérifie qu'elle est de type POST
        if ($request->getMethod() == 'POST') {
            // On fait le lien Requête <-> Formulaire
            $form->handleRequest($request);

            // Vérifier si les entrées sont correctes
            if ($form->isValid()) {
                // On enregistre l'objet en base de donnée
                $em = $this->getDoctrine()->getManager();
                $em->persist($suggestArticle);
                $em->flush();

                // On redirige vers la page de visualisation du contenu nouvellement créé
                return $this->redirect($this->generateUrl('suggest', array('id' => $suggestArticle->getId())));
            }
        }

        return $this->render('ESGIBlogBundle:Article:addSuggestArticle.html.twig', array(
            'form' => $form->createView(),
            'categories' => $categories,
        ));
    }

    public function editAction(Article $article)
    {
        $form = $this->createForm(new ArticleType(), $article);

        $request = $this->get('request');

        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);

            // Vérifier si les entrées sont correctes
            if ($form->isValid()) {
                // On enregistre l'objet en base de donnée
                $em = $this->getDoctrine()->getManager();
                $user = $this->container->get('security.context')->getToken()->getUser();
                $article->setUser($user);
                $em->persist($article);
                $em->flush();

                // On définit un message flash
                $this->get('session')->getFlashBag()->add('info', 'Article bien modifié');
                //On redirige vers la page de visualisation du contenu nouvellement créé
                return $this->redirect($this->generateUrl('see', array('id' => $article->getId())));
            }
        }

        return $this->render('ESGIBlogBundle:Article:edit.html.twig', array(
            'article' => $article,
            'form'    => $form->createView(),
            'categories' => $categories,
        ));
    }


    public function searchAction() {

        $numberContentsByPage = 3;
        $page = 1;

        $request = $this->get('request');
        $categories = $this->getDoctrine()->getManager()->getRepository("ESGIBlogBundle:Category")->findAll();
        $articles = null;
        // On vérifie qu'elle est de type POST
        if ($request->getMethod() == 'POST') {
            // On fait le lien Requête <-> Formulaire
            $key = $request->request->get('key', '');

            // Sinon, on créer une pagination avec un nombre de contenu constant pour chaque page.
            $articles = $this->getDoctrine()
                ->getManager()
                ->getRepository('ESGIBlogBundle:Article')
                ->getArticlesWithKey($key);
        }

        return $this->render('ESGIBlogBundle:Article:results.html.twig', array(
            'articles' => $articles,
            'categories' => $categories,
        ));

        //return $this->redirect($this->generateUrl('articles'));
    }
}

src/ESGI/BlogBundle/Resources/views/Article/add.html.twig
{% extends 'ESGIBlogBundle::layout.html.twig' %}

{% block title %}{% trans %}Ajouter un article {% endtrans %}{% endblock %}

{% block blog_body %}
<h1>Welcome to the Article:add page</h1>
    {% include "ESGIBlogBundle:Article:form.html.twig" %}

{% endblock %}

src/ESGI/BlogBundle/Resources/views/Article/addSuggestArticle.html.twig
{% extends 'ESGIBlogBundle::layout.html.twig' %}

{% block title %}{% trans %}Ajouter un article {% endtrans %}{% endblock %}

{% block blog_body %}
    <h1>Suggérer un article</h1>
    {% include "ESGIBlogBundle:Article:form.html.twig" %}

{% endblock %}

src/ESGI/BlogBundle/Resources/views/Article/articles.html.twig
{% extends "ESGIBlogBundle::layout.html.twig" %}

{% block title %}ESGIBlogBundle:Article:articles{% endblock %}

{% block blog_body %}


  



    {# Afficher les contenus #}
        <header class="intro-header" style="background-image: url({{ asset('img/home-bg.jpg') }})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Blog Symfony</h1>
                        <hr class="small">
                        <span class="subheading">phrase d'accroche qui envoie du lourd</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class = "container">
    
   
    
     <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              
        {% for article in articles %}
         <div class="row">
              <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            <a href="{{ path('see', {'id': article.id}) }}">{{ article.title }}</a>
                        </h2>
                       
                    </a>
                    <p class="post-meta">Posted by {{ article.user.username }} on September 24, 2014</p>
                </div>
            </div>
        {% else %}
            <p>{{'Pas de contenus disponible.'|trans}}</p>
        {% endfor %}
        </div>
    </div>

    {# Pagination #}
    <nav class="text-center">
        <ul class="pagination">
            {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
            {% for p in range(1, numberPage) %}
                <li{% if p == page %} class="active"{% endif %}>
                    <a href="{{ path('articles', {'page': p}) }}">{{ p }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>
{% endblock %}

src/ESGI/BlogBundle/Resources/views/Article/delete.html.twig
{% extends "::base.html.twig" %}

{% block title %}ESGIBlogBundle:Article:delete{% endblock %}

{% block body %}
<h1>Welcome to the Article:delete page</h1>

    <h2>{{'Supprimer'|trans}} {{ article.title }}</h2>

    <p>
        {% trans %}Etes-vous certain de vouloir supprimer l'article {% endtrans %} "{{ article.title }}" ?
    </p>

    {# On met l'id de l'article dans la route de l'action du formulaire #}
    <form action="{{ path('delete', {'id': article.id}) }}" method="post">
        <a href="{{ path('see', {'id': article.id}) }}" class="btn">
            <i class="icon-chevron-left"></i>
            {{'Retour aux articles'|trans}}
        </a>
        <input type="submit" value="Supprimer" class="btn btn-danger" />
        {{ form_rest(form) }}
    </form>
{% endblock %}

src/ESGI/BlogBundle/Resources/views/Article/form.html.twig
{% form_theme form 'bootstrap_3_layout.html.twig' %}
<h3>{{'Formulaire Contenu'|trans}}</h3>

{# Ici on laisse vide la vue pour l'instant, on la comblera plus tard lorsqu'on saura afficher un formulaire #}
<div class="">
    <form method="post" role="form" {{ form_enctype(form) }} >
        {# {% form_theme form 'TellmediaTemplateBundle:Form:fields.html.twig' %} #}

        {# Reste du formulaire #}
        {{ form_widget(form) }}
        <br>
        <input type="submit" class="btn btn-success" />
    </form>
</div>

src/ESGI/BlogBundle/Resources/views/Article/results.html.twig
{% extends "ESGIBlogBundle::layout.html.twig" %}

{% block title %}ESGIBlogBundle:Article:results{% endblock %}

{% block body %}
    <h1>Welcome to the Article:articles result page</h1>

    <h3><a href="{{ path('articles', {'id': 0}) }}">{{ 'Toutes'|trans }}</a></h3>
    {% for category in categories %}
        <h3><a href="{{ path('articles', {'id': category.id}) }}">{{ category.name }}</a></h3>
    {% endfor %}

    {# Formulaire de Recherche #}
    <div class="row content-search">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            {% include "ESGIBlogBundle:Article:search.html.twig" %}
        </div>
    </div>

    {# Afficher les contenus #}
    <div class="row">
        {% for article in articles %}
            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">
                    <img src="{{ asset(article.image.webPath) }}" alt=""/>
                    <div class="caption">
                        <h3><a href="{{ path('see', {'id': article.id}) }}">{{ article.title }}</a></h3>
                    </div>
                </div>
            </div>
        {% else %}
            <p>{{'Pas de contenus disponible.'|trans}}</p>
        {% endfor %}
    </div>
{% endblock %}

src/ESGI/BlogBundle/Resources/views/Article/search.html.twig
<form method="post" action="{{ path('article_search') }}" class="navbar-form navbar-left" role="search">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="{{'Rechercher'|trans}}" name="key" size="40">
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></button>
    </div>
</form>

src/ESGI/BlogBundle/Resources/views/Article/see.html.twig
{% extends "ESGIBlogBundle::layout.html.twig" %}

{% block title %}ESGIBlogBundle:Article:see{% endblock %}

{% block blog_body %}
    <header class="intro-header" style="background-image: url({{ asset(article.image.webPath)}})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ article.title }}</h1>
                        <hr class="small">
                        <span class="subheading"><i>{{ 'Article rédigé par'|trans }} {{ article.user.username }} le {{ article.updated|date('d-M-y') }}</i></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class = "container">


    <p>{{ article.body }}</p>
    

    {% if article.isCommented == true %}
        <p><a href="{{ path('add_comment', {'id': article.id}) }}" class="btn btn-danger" role="button">{{'Ajouter un commentaire'|trans}}</a></p>
    {% endif %}


          <div class="box box-info">
            <div class="box-header">
              
                <h3 class="box-title">{{ 'Commentaires'|trans }}</h3>
            </div><!-- /.box-header -->
        </div>

{% for comment in article.comments %}
    <div class="col-md-12">
  
        <div style = "margin-top:-15px;">
            <h5> <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></h5>
            <div style = "margin-top:-25px;">
                <p>{{ comment.content }}</p>
            </div>
            <div style = "margin-top:-30px; margin-bottom:15px">
                <i>{{'Le'|trans}} {{ comment.updated|date('d/m/Y') }}</i>
                <br />
            </div>
        </div>
    </div>


    {% else %}
        <p>{% trans %} Pas de commentaires. {% endtrans %}</p>
    {% endfor %}
{% endblock %}

src/ESGI/BlogBundle/Resources/views/Article/suggest.html.twig
{% extends "ESGIBlogBundle::layout.html.twig" %}

{% block title %}ESGIBlogBundle:Article:articles{% endblock %}

{% block body %}
    <h1>Liste des suggestions</h1>
    {# Afficher les contenus #}
    <div class="row">
        {% for article in articles %}
            <div class="col-sm-4 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>{{ article.title }}</h3>
                        <p>{{ article.body }}</p>
                    </div>
                </div>
            </div>
        {% else %}
            <p>{{'Pas de contenus disponible.'|trans}}</p>
        {% endfor %}
    </div>

    {# Pagination #}
    <nav class="text-center">
        <ul class="pagination">
            {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
            {% for p in range(1, numberPage) %}
                <li{% if p == page %} class="active"{% endif %}>
                    <a href="{{ path('articles', {'page': p}) }}">{{ p }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>
{% endblock %}